apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: test-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-cluster
  template:
    metadata:
      labels:
        app: redis-cluster
    spec:
      containers:
      - name: redis-cluster
        image: redis:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 6379
        volumeMounts:
          - mountPath: /etc/redis
            name: redis-config
        command:
          - "redis-server"
          - "/etc/redis/redis.conf"
      volumes:
        - name: redis-config
          configMap:
            name: redis-configmap
            items:
              - key: redis.conf
                path: redis.conf
